### PR TITLE
Update user-agent

### PR DESCRIPTION
**Pull request by assafmo**
The User-Agent `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0` is probably blocked by addic7ed

### CODE REVIEW

**Comment by same31** [comment]
Hello, maybe you issued to many downloads and are blocked now?
Anyway, I think it is a good thing to update the UA, thanks for your contribution.

**Comment by assafmo** [comment]
Ohh... I think you are right. I get HTTP 304 but when I change the UA it stops and then returns.  
I think I'll try adding `Cache-Control: no-cache` and `Pragma: no-cache` and check if it works.

**Comment by same31** [comment]
I think there is a limit of 40 downloads a day by IP address from addic7ed.com

**Comment by assafmo** [comment]
Weird, It just started this week. I remember downloading a lot more than 40 subtitles some days.

**Comment by same31** [comment]
That's what I read on the main page, maybe it's related to your issue :) :

2 days ago |   | Problems are fixed, we are back to normal. |  
  | 3 days ago |   | We're experiencing some issues, so we might be unreachable or very slow today. And our search engine isn't working. We're working on fixing it. Hang on.

**Comment by assafmo** [comment]
Thanks.  
`Cache-Control: no-cache` and `Pragma: no-cache` doesn't change anything. I still get HTTP 304.

**Comment by same31** [comment]
Oh you are absolutely right... Just tried it and I have a weird 304 as well when issuing a search.
I will have a look :)

**Comment by same31** [comment]
Ok I fixed it, the search URL has changed from search.php to srch.php.
Thank you for pointing this issue out!

**Comment by assafmo** [comment]
Wow, Thanks!

**Comment by assafmo** [comment]
Could you also add a boolean hearing-impaired field to the `subInfo` object?

**Comment by same31** [comment]
I would be more than happy to receive your pull request for this :)

**Comment by assafmo** [comment]
#4 :smile:

**Pull request merged**
